import json
# Imports Python's JSON module.
# We use this to format the network evidence before sending it to the AI.


from app.intent_engine import load_network_intent
# Imports the function that loads our expected network design.


from app.evidence_collector import collect_network_evidence
# Imports the function that connects to the routers
# and collects live troubleshooting information.


from app.ollama_client import ask_ollama
# Imports the function that sends a prompt to Ollama
# and receives the AI response.


def main():
    # This is the main function that runs NetPilot.


    print("\n===== NETPILOT v0.2 =====\n")
    # Prints the NetPilot title.


    print("Loading network intent...")
    # Lets us know that NetPilot is loading
    # the expected network design.


    intent = load_network_intent()
    # Loads the information from network_intent.json.


    print("Collecting live network evidence...\n")
    # Lets us know that NetPilot is about to connect
    # to the routers and collect live information.


    evidence = collect_network_evidence()
    # Connects to R1, R2, and R3 and collects
    # the OSPF troubleshooting information.


    intent_text = json.dumps(intent, indent=2)
    # Converts the network intent dictionary into
    # nicely formatted text for the AI.


    evidence_text = json.dumps(evidence, indent=2)
    # Converts all of the live router evidence into
    # nicely formatted text for the AI.


    prompt = f"""
You are NetPilot, an AI network troubleshooting agent.

You are troubleshooting a Cisco OSPF network.

You have two important sources of information.

==================================================
NETWORK INTENT
==================================================

This is how the network is supposed to be configured:

{intent_text}

==================================================
LIVE NETWORK EVIDENCE
==================================================

This is the actual information collected directly from
the Cisco routers:

{evidence_text}

==================================================
YOUR TASK
==================================================

Compare the LIVE NETWORK EVIDENCE against the NETWORK INTENT.

Determine:

1. What network behavior is currently broken?

2. Which OSPF adjacency or connectivity is missing?

3. Which router or routers are affected?

4. What evidence proves the problem?

5. Which specific router is violating the intended network design?

6. Do NOT recommend changing a correctly configured router
   just to match a misconfigured router.

7. Use the NETWORK INTENT as the source of truth.

8. Identify the exact interface and configuration that
   should be corrected.

9. Provide the Cisco commands required to fix the problem.

10. Explain your reasoning in a way that a network engineer
    can verify.

Respond using these sections:

PROBLEM

AFFECTED DEVICES

EVIDENCE

ROOT CAUSE

DEVICE VIOLATING NETWORK INTENT

RECOMMENDED FIX

CONFIDENCE LEVEL
"""

    print("Sending evidence to Ollama and Qwen...\n")
    # Displays a message showing that NetPilot is now
    # sending the real network evidence to the AI.


    answer = ask_ollama(prompt)
    # Sends the prompt to Ollama.
    # Ollama passes the prompt to your local qwen2.5:32b model.


    print("\n===== NETPILOT AI DIAGNOSIS =====\n")
    # Prints a heading for the AI's response.


    print(answer)
    # Displays the diagnosis generated by Qwen.


if __name__ == "__main__":
    # Checks whether this Python file is being run directly.


    main()
    # Starts NetPilot.